### ISSUE TITLE
Just dungeons?

### ISSUE THREAD

**Issue by machado-rev** [fabian57fabian/archero_bot_57#1]
He does only dungeons or normal phases?

**Comment by fabian57fabian** [comment]
For now it just tries to do the Cave (Number 6 dungeon). I'm currently working on it

**Comment by machado-rev** [comment]
I've adjusted in terms to my phone (K12+) but I don't know much of sizes
for the screen
Will make some pull requests later

Em qui, 6 de fev de 2020 5:54 PM, Fabian <notifications@github.com>
escreveu:

**Comment by fabian57fabian** [comment]
I've calculated locations of buttons taking a few screenshots and then pointing in the center or left/right part of some buttons.
Feel free to add code and data.

**Comment by machado-rev** [comment]
Fabian, can you explain how you had calculated the points? 

If you look here https://github.com/fabian57fabian/archero_bot_57/blob/master/static_bot_cave.py#L16

You have a perfect positioning but I can't use it to my phone that the screen are 720*1440

Have a tutorial?

**Comment by fabian57fabian** [comment]
I've taken some screenshots and looked at x,y coordinates in the center of the buttons. I'll explain and put some screenshots as soon as possible

**Comment by fabian57fabian** [comment]
Can you post a screenshot with home state, starting dungeon, selecting on power up and spin state

**Comment by machado-rev** [comment]
Thanks, I found how to do with point tracking!

When finish for K12+ I will make a pull request with the name of K12+.

Will try lower dungeon too.

**Comment by fabian57fabian** [comment]
Added my screenshots on last commit.
Fixed #issuecomment-583110739 by adding normalization coordinates before main width and height.
Also added coordinates check. you can check your own coordinates now @machado-rev

**Comment by machado-rev** [comment]
Thanks brother, I will send a pull request soon!
