### ISSUE TITLE
Chapter 3 not working

### ISSUE THREAD

**Issue by craftpiwurzel** [fabian57fabian/archero_bot_57#11]
**Describe the bug**
Chapter 3 is not working for me. At the end of room 1 he does not go through the door. 
Then I took him manually to the next room and started again from there. The same thing happened to the boss room.

**Hardware description**
 - Smartphone: Huawei Mate 20 Pro
 - Screen size: 1080x2340
 - Computer OS: Windows 10

**Video**
https://drive.google.com/file/d/14FxSGQXKt63v3lZ8jhDPCxeaIiDS5g5i/view?usp=sharing

**Comment by fabian57fabian** [comment]
Thank you for the bug. With last commit he will stay on left side and finally always exit.
Try it and let me know if it fails again.
If no answer given in 5 days, closing the issue.

**Comment by craftpiwurzel** [comment]
Thanks it's working now.
