### ISSUE TITLE
Chapter 3 Room 6 Mysterious Vendor

### ISSUE THREAD

**Issue by craftpiwurzel** [fabian57fabian/archero_bot_57#12]
**Describe the bug**
Unfortunately I found another thing where the bot doesn't work anymore.
If you play room 6 and the player can go all the way into the corners.
Then you choose your reward / skill at the end and the bot wants to go to the next room. But then comes the Mysterious Vendor.
The program thinks that he is already further and is then out of sync.
This only happens if there is nothing in the corners of the room and the player can go into the corners.

**Hardware description**
 - Smartphone: Huawei Mate 20 Pro
 - Screen size: 1080x2340
 - Computer OS: Windows

**Video**
[Made a video again](https://drive.google.com/file/d/13THqXR4GCfYiwmK9ffs4siMII4mxjswY/view?usp=sharing)

**Additional context**
By the way the Mysterious Vendor always comes at the end of room 6.
#10 Do not know if the same problem occurs there.

**Comment by fabian57fabian** [comment]
Reverting to latest commit with some changes.
Putting back centered character, using centering function to exit dungeon.
I'll push soon

**Comment by fabian57fabian** [comment]
Please pull the changes and test again

**Comment by craftpiwurzel** [comment]
Now it doesn't even work anymore. Sorry
The centering function only works if there is nothing in the corners. Otherwise it runs too far to the right. 
In the end he always wants to go through the gate to the top right, but the gate is on the top left.
If you change it so that it always runs to the top left at the end, it should work.
You have to be careful not to change it in the Boss Rooms, it works there because he stands slightly to the left of the gate and then goes through to the top right.

**Comment by fabian57fabian** [comment]
I'll put the test:FAIL under dungeon 3. will solve it later.

**Comment by fabian57fabian** [comment]
Dungeon 3 is still under development. New push will be coming soon. Closing because of not ended feature
