### ISSUE TITLE
Randomizing Level-Up Picks

### ISSUE THREAD

**Issue by DustyDiamond** [fabian57fabian/archero_bot_57#13]
Maybe you could Randomize the picks after Level up with a random number between 1-3. :)

**Comment by fabian57fabian** [comment]
Please define "Randomize picks"

**Comment by DustyDiamond** [comment]
After every Level-Up you can choose from 3 Perks/Ability to upgrade the run. Correct me if i'm wrong, but it seems the bot always picks the left one.
It would be nice if the bot would pick any other perk not only the left. I know it would be very much to ask for recognition of the perks to choose the best, but maybe the bot could choose a random perk. For that it would have to roll a random number between 1 and 3 and pick left, middle or right dependent on that random number. ;)

**Comment by fabian57fabian** [comment]
Ok, by "picks" you meant "abilities".
I'm planning on creating a detector soon and create an ordered tier list.
As for the ability pick, i choosed to pick left because i read that abilities are saved randomly, so picking randomly between the 3 of them or choosing the left one is the same in terms of randomness.
Would you still like the randomness feature?

**Comment by DustyDiamond** [comment]
I think since you are already working on a detector and a tier list, it isn't really necessary. My idea was to make the bot less detectable for not picking left all the time ^^
I don't know how good they are in such detections.

**Comment by fabian57fabian** [comment]
Well that is a good reason.
Adding feature soon

**Comment by DustyDiamond** [comment]
Sounds nice, maybe add the detection (if not already planned) for Heal-Stages to not choose GP up. 
Or if possible let the user edit the tier list in the overlay (for abilities and Heal/max GP) 
:)
