### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by Lethtel** [fabian57fabian/archero_bot_57#15]
Hey again ! 

Thought about out of sync', i noticed 2 cases : 
- OOS resulting in not a good screen detection, the bot think (in my case) that it's at the lobby when it's still in game.
- OOS resulting in "i detect something wrong", so it left, letting us in whatever screen we are.

In first case (for me at least) the bot finish by looping in "No energy left".
We could add a count for when this is detected.
To launch a game we need 5 energy, roughly an hour, if we not detect enough energy for more then 2h => Kill archero, reopen it and leave the previous run (big red button).
We should next check for Afk reward / exceptionnal offer as the window may appear.

In 2nd case : the bot just stop for not clicking every where.
Instead of leaving, we could do the same as above : leave the game-reopen it.

You can make it wait for whatever time you want but i think the loop shouldn't exceed 3hours (as we need 4 hours to get full energy charged).

adb commands to start the app :
adb shell monkey -p com.habby.archero -v 1

Not the "real" commands, but to start with package name we need to now activity, i suspect this to change depending on the environnement (emulator or real phone) but idk, this workaround works for me.

To close the app : 
adb shell am force-stop com.habby.archero

Regards,

**Comment by fabian57fabian** [comment]
Hello @Lethtel 
Killing the game is one thing that will not be done.
Better improve detection that using a rough failing one and closing/reopening.
Besides that closing and reopening an app will raise more and more troubles in case of failure.

I'll update the repo once the last bug (stuck in level 18) will be completed.
Then close this issue if no other advises/comments received

**Comment by fabian57fabian** [comment]
Closed because no advises/comments received
