### ISSUE TITLE
Stuck at level 3 after angel healing

### ISSUE THREAD

**Issue by porast1** [fabian57fabian/archero_bot_57#23]
I got stuck on level 3 after angel healing.

**Comment by fabian57fabian** [comment]
Hello,
Could you please provideyour device type or Nox version+PC details.
It seems to me that different devices (having maybe slower CPUs) may slow down the application and fail to move accordingly on the screen.
It's just an idea but it could help the bot.

**Comment by porast1** [comment]
Nox is V.7.0.1.2. My PC: lenovo y50-70, gtx 860M, i7-4710HQ, 15,6".
Describing the problem, the character stays at level 3 and the program continues to level 20.

**Comment by fabian57fabian** [comment]
Hi @porast1 
I manually tested to replicate this bug on higher-end workstations as well ass low-end pc/laptops.
I never managed to get stuck at level 3.
Maybe one of the latests commits solved it.

Since no further comments were made, i am closing the issue.
