### ISSUE TITLE
No longer checking quickraid

### ISSUE THREAD

**Issue by dstea123** [fabian57fabian/archero_bot_57#26]
**Describe the bug**
Since new update, the program is no longer checking for QuickRaid.

**Hardware description**
Noxplayer 7.0.2.0
Screen size:  1080x1920

**Screenshots**
![image](https://user-images.githubusercontent.com/98632780/151648227-458690c2-3ffe-41d7-9fed-dd173ae9f355.png)

**Comment by fabian57fabian** [comment]
Thank you for the bugreport.
I'll soon start updating it
