### ISSUE TITLE
Stuck at Master on Chapter 6/10 level 1

### ISSUE THREAD

**Issue by Revuin** [fabian57fabian/archero_bot_57#32]
Love the new update and settings but it's consistently getting stuck when the Master appears in Chapter 6 or 10 level 1. 

The error is **'CaveEngine' object has no attribute 'battle_pass_rewards'**

![image](https://user-images.githubusercontent.com/20654538/180014750-e0f1f4ee-c034-4aea-b36b-4ce20756267c.png)

 - Nox Emulator 7.0.3.1
 - Screen size: 1080x1920
 - Computer OS: Windows 10

**Comment by Revuin** [comment]
I found a workaround in case anyone else is having the same issue. 

1. Open CaveDungeonEngine.py
2. Go to line 733
3. Change
if self.battle_pass_advanced or **self.battle_pass_rewards:**
to
if self.battle_pass_advanced or **self.battle_pass_advanced:**

**Comment by Revuin** [comment]
It's working. Now it clicks the back button instead of giving that error

**Comment by AdminZero** [comment]
> 3\. or **self.battle_pass_rewards**

Sorry, that feature was not implemented...
Open CaveDungeonEngine.py
Go to line 733
Change
if self.battle_pass_advanced or self.battle_pass_rewards:
to
if self.battle_pass_advanced:

@fabian57fabian I made some updates to AdminZero fork if you haven't noticed.
