### ISSUE TITLE
Attempts to start dungeon with 4 energy

### ISSUE THREAD

**Issue by Revuin** [fabian57fabian/archero_bot_57#33]
The bot will try to start a dungeon when there is only 4 energy instead of waiting for 5 energy. Please see attached video

https://user-images.githubusercontent.com/20654538/180633253-4edd7b72-2230-4cc1-a817-e29c7edf36c6.mp4

**Comment by AdminZero** [comment]
The newest game Archero version 4.0.3 moved the energy bar slightly... to fix:
1. Open folder: archero_bot_57 > datas > 1080x1920 > coords
2. Edit file: static_specific_coords.json
3. Change: line #3 from:  "coordinates": [[0.3305555555555556, 0.02708333333333]],
4. Change: line #3 to: "coordinates": [[0.**3445555555555556**, 0.02708333333333]],
5. Save changes
6. close bot, reboot

**Comment by Revuin** [comment]
Worked perfectly, thank you

**Comment by fabian57fabian** [comment]
Closed because of problem solved
