### ISSUE TITLE
After running for half a day, getting error "Unable to allocate 31.6 MiB for an array with shape (2073600, 4) and data type int32"

### ISSUE THREAD

**Issue by Revuin** [fabian57fabian/archero_bot_57#34]
After running for maybe 8 hours, the bot keeps getting error "Unable to allocate 31.6 MiB for an array with shape (2073600, 4) and data type int32"

This didn't happen before the big update. Could the bot be storing stuff into memory without clearing it?

![image](https://user-images.githubusercontent.com/20654538/183175853-5a071102-090c-4bc6-bfd0-9e9f7c0a7134.png)

**Comment by AdminZero** [comment]
Hmm.. I have got that error before too, but usually when multitasking on the PC that is running the bot (for example when trying to run the bot in the background and playing Minecraft).  

Possible Solution: Try rebooting the PC, and only let the bot run by itself.  

How often does it happen, every 8 hours? or only when trying to multitask? or other (explain more if you can)?

I will look into it, it might have something to do with the additional door checks in the LetPlay function, but that's all I can think of.

Additionally: you can try the experimental versions on the AdminZero fork to see if that fixes it, until Fabian has time to check.

**Comment by Revuin** [comment]
It does seem to happen only when multitasking. For example, I'll start up
the bot and YouTube on Google Chrome to play overnight. Youtube is
auto-playing video after video. In the morning, I'll always get that error.

Thanks, I'll give the other versions a try.

**Comment by Revuin** [comment]
A couple things I wanted to add:

1. It happened again after about 8 hours but I was not multitasking on it. I did not restart the PC though.

2. AdminZero's version has been running for a full day so far without any issues

**Comment by AdminZero** [comment]
> 

Good to know!  Yeah, I used to have to reboot the PC to get that memory error to go away before, but I have not seen it recently since using the latest experimental version; I also have not been multitasking on the laptop recently either.

**Comment by fabian57fabian** [comment]
I've also seen this problem only when multitasking.
The bot uses a small amount of memory and deletes memory every time it takes a screen from adb and resets all lists.
When running for long periods with a small amount of memory, it can happen due to some periodic high memory usage-and-release.
Since it never happened since last time, i am closing this issue.
