### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by VietChaien** [fabian57fabian/archero_bot_57#4]
Hi guy, i have problem, can you help me check it ?

> Traceback (most recent call last):
>   File "static_bot_cave.py", line 2, in <module>
>     from pure_adb_connector import *
>   File "/Users/phandung/Downloads/archero_bot_57/pure_adb_connector.py", line 35
>     def adb_screen(name:str = "screen.png"):
>                        ^
>

**Comment by fabian57fabian** [comment]
This bug was fixed in one of previous commits.
Last commit was 6 hours ago.
Please pull the new updates (or simply download again the repo).
Could you write your device size? E.g. when starting the bot read the width and height written.

**Comment by fabian57fabian** [comment]
Also post the phone model

**Comment by fabian57fabian** [comment]
No answer received after 5 days. Closing the issue
