### ISSUE TITLE
"Do you wish to debug?" GameScreenConnector arguments

### ISSUE THREAD

**Issue by xhek** [fabian57fabian/archero_bot_57#5]
**Describe the bug**
check_static_coords.py ln 36, arguments, crash see below

**Hardware description**
 - Smartphone: OnePlus 6
 - Screen size: 1080x2280
 - Computer OS: Windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/37110154/78881474-29305c00-7a57-11ea-9154-a3f4fcb215e8.png)

**Additional context**

F:\Desktop\archero_bot_57-master>python check_static_coords.py
0: 1080x1920
1: 1080x2220
2: 1080x2280
3: 1080x2340
Select your number2
Using datas\1080x2280\screens
Do you wish to debug? (set yes only if you did it already once and found some rows with NO_DETECTION): (y/n):n
Traceback (most recent call last):
  File "check_static_coords.py", line 36, in <module>
    screen_conector = GameScreenConnector(width, heigth)
TypeError: __init__() takes 1 positional argument but 3 were given

**Comment by fabian57fabian** [comment]
Fixed. Please check if it works

**Comment by fabian57fabian** [comment]
Assuming bug is fixed. Closing issue
