### ISSUE TITLE
Using Android Emulator for bot usage

### ISSUE THREAD

**Issue by xhek** [fabian57fabian/archero_bot_57#6]
**Is your feature request related to a problem? Please describe.**
I would like to run the bot my computer using LDPlayer4 (or Nox, BlueStack..) emulator

**Describe the solution you'd like**
I want to run the game with bot on the emulator without having my smartphone active

**Describe alternatives you've considered**
No alternative considered

**Comment by fabian57fabian** [comment]
Fixed with commit 333b3786793ae08b59a1e1056f2eafdeb122fdf7

**Comment by fabian57fabian** [comment]
Nox emulator support was added.
Future releases may include support for other emulators, but right now i'll be focusing on making it perfectly work with Nox.
Closing issue because of feature added.
