### ISSUE TITLE
Choose from another dungeons

### ISSUE THREAD

**Issue by Sol4rius** [fabian57fabian/archero_bot_57#7]
Hey,
please make a possibility to choose from chpt. 3, 6 (or 10). I found out my character with farming bot on can't beat chpt. 6 at all. Moreover I usually get 1-2 items per chpt.3 and 0 items from chpt.6..

thank you!

**Comment by fabian57fabian** [comment]
You're the second person to ask. I'll add to the features required. Thanks for the interest.

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 13, 2020 at 18:12, Sol4rius<notifications@github.com> wrote:   


Hey,
please make a possibility to choose from chpt. 3, 6 (or 10). I found out my character with farming bot on can't beat chpt. 6 at all. Moreover I usually get 1-2 items per chpt.3 and 0 items from chpt.6..

thank you!

**Comment by fabian57fabian** [comment]
Also, if you liked the project, a star will be great! 

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 13, 2020 at 18:12, Sol4rius<notifications@github.com> wrote:   


Hey,
please make a possibility to choose from chpt. 3, 6 (or 10). I found out my character with farming bot on can't beat chpt. 6 at all. Moreover I usually get 1-2 items per chpt.3 and 0 items from chpt.6..

thank you!

**Comment by Sol4rius** [comment]
Starred!

**Comment by Sol4rius** [comment]
Hey! May I ask you, is there any progress?

**Comment by fabian57fabian** [comment]
Hello there.The priority is fixing some other bugs.I've completed the emulator feature so i'll start soon.I'll let you know
Sent from Yahoo Mail on Android 
 
  On Sat, Apr 18, 2020 at 15:06, Sol4rius<notifications@github.com> wrote:   


Hey! May I ask you, is there any progress?

**Comment by fabian57fabian** [comment]
With last commit i added Dungeons 3, 6, 10.
Click the image and select the dungeon you want to play.
Closing issue because of feature correctly added.
