### ISSUE TITLE
Inaccurate Energy Detection

### ISSUE THREAD

**Issue by k-i-p-z** [fabian57fabian/archero_bot_57#8]
**Describe the bug**
Getting "No energy left" message even though I have more than 5 energy.

**Hardware description**
 - Smartphone: Huawei Mate 20 Pro
 - Screen size: 1080x2340
 - Computer OS: Windows

**Screenshots**
![not enough energy](https://user-images.githubusercontent.com/64004775/79732670-96c96b80-8326-11ea-8e7e-837de255347d.PNG)
![ingame](https://user-images.githubusercontent.com/64004775/79733044-1c4d1b80-8327-11ea-866f-1016fb0d7d42.jpg)

**Additional context**

**Comment by fabian57fabian** [comment]
Fixed coordinate height check. Working on given screenshot and others in data folder.
Thanks for the issue.
Being fixed, i'll close the issue.
